permissions:
  contents: write

on:
  [push]

jobs:
  build:
    name: Auto Release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
            python-version: "3.11"
      - name: Install Dependencies
        run: pip install -r requirements.txt
      - name: Install Build Dependencies
        run: pip install nuitka imageio
      - name: Build
        run: python build.py
      - name: Auto release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: ${{ matrix.os }}
          prerelease: true
          files: |
            dist/*